from util.database import db

rows = db.query("""SELECT TOP (1000) [PersoneriaID]
      ,[TipoIdentidadID]
      ,[NroIdentidad]
      ,[GrupoPersoneria]
      ,[Personeria]
      ,[NombreComercial]
      ,[Domiciliado]
      ,[TipoContribuyente]
      ,[FamiliaID]
      ,[NegocioID]
      ,[CtaDetraccion]
      ,[Codigo]
      ,[Estado]
      ,[UsuarioID]
      ,[FechaCreacion]
      ,[FechaModificacion]
      ,[ConvenioID]
      ,[MedioRegistroID]
      ,[MedioInformacionID]
      ,[Referencia]
      ,[Telefonos]
      ,[email]
      ,[fechanacimiento]
      ,[universidadid]
      ,[fechacolegiatura]
      ,[vitalicio]
      ,[Foto]
      ,[libro]
      ,[genero]
      ,[FechaDefuncion]
      ,[password]
      ,[estadoCivil]
      ,[NumHijos]
      ,[ListaPrecioId]
      ,[PermisoEoRsPDF]
  FROM [db_a9d155_ecomisti].[dbo].[Personeria]""", (25,))
for row in rows:
    print(row.PersoneriaID, row.Personeria)
